"""init schema

Revision ID: 02b38ee6bcc9
Revises: 
Create Date: 2025-09-10 18:00:58.349849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b38ee6bcc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email_contato', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('laudo_microbiologico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_coleta', sa.DateTime(), nullable=False),
    sa.Column('tipo_amostra', sa.String(length=100), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=False),
    sa.Column('resultado', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.Enum('SUPER_ADMIN', 'ADMIN', 'AUDITOR', 'GESTOR', 'VISUALIZADOR', name='tipousuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('primeiro_acesso', sa.Boolean(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('versao', sa.String(length=10), nullable=True),
    sa.Column('pontuacao_ativa', sa.Boolean(), nullable=True),
    sa.Column('pontuacao_maxima', sa.Float(), nullable=True),
    sa.Column('peso_total', sa.Float(), nullable=True),
    sa.Column('exibir_pontuacao', sa.Boolean(), nullable=True),
    sa.Column('exibir_observacoes', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('publicado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_formulario.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('loja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('gerente_nome', sa.String(length=100), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', 'APROVADA', name='statusauditoria'), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('pontuacao_obtida', sa.Float(), nullable=True),
    sa.Column('pontuacao_maxima', sa.Float(), nullable=True),
    sa.Column('percentual', sa.Float(), nullable=True),
    sa.Column('observacoes_gerais', sa.Text(), nullable=True),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario.id'], ),
    sa.ForeignKeyConstraint(['loja_id'], ['loja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('bloco_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_resposta', sa.Enum('SIM_NAO_NA', 'SIM_NAO', 'TEXTO', 'TEXTO_LONGO', 'NUMERO', 'NOTA', 'PERCENTUAL', 'MULTIPLA_ESCOLHA', 'UNICA_ESCOLHA', 'IMAGEM', 'DATA', 'HORA', 'DATA_HORA', name='tiporesposta'), nullable=False),
    sa.Column('obrigatoria', sa.Boolean(), nullable=True),
    sa.Column('permite_observacao', sa.Boolean(), nullable=True),
    sa.Column('permite_foto', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('pontuacao_maxima', sa.Float(), nullable=True),
    sa.Column('valor_esperado', sa.String(length=255), nullable=True),
    sa.Column('limite_minimo', sa.Float(), nullable=True),
    sa.Column('limite_maximo', sa.Float(), nullable=True),
    sa.Column('critica', sa.Boolean(), nullable=True),
    sa.Column('gera_nc_automatica', sa.Boolean(), nullable=True),
    sa.Column('bloco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bloco_id'], ['bloco_formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcao_pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.String(length=100), nullable=True),
    sa.Column('pontuacao', sa.Float(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('gera_nc', sa.Boolean(), nullable=True),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_texto', sa.Text(), nullable=True),
    sa.Column('valor_numero', sa.Float(), nullable=True),
    sa.Column('valor_boolean', sa.Boolean(), nullable=True),
    sa.Column('valor_data', sa.DateTime(), nullable=True),
    sa.Column('valor_opcoes_selecionadas', sa.Text(), nullable=True),
    sa.Column('nao_aplicavel', sa.Boolean(), nullable=True),
    sa.Column('pontuacao_obtida', sa.Float(), nullable=True),
    sa.Column('pontuacao_maxima', sa.Float(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('foto_evidencia', sa.String(length=255), nullable=True),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('auditoria_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditoria.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nao_conformidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=True),
    sa.Column('tipo', sa.Enum('CRITICA', 'MAIOR', 'MENOR', 'OBSERVACAO', name='tiponaoconformidade'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('data_identificacao', sa.DateTime(), nullable=True),
    sa.Column('prazo_resolucao', sa.DateTime(), nullable=True),
    sa.Column('data_resolucao', sa.DateTime(), nullable=True),
    sa.Column('auditoria_id', sa.Integer(), nullable=False),
    sa.Column('resposta_id', sa.Integer(), nullable=True),
    sa.Column('identificado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditoria.id'], ),
    sa.ForeignKeyConstraint(['identificado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['resposta_id'], ['resposta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nao_conformidade')
    op.drop_table('resposta')
    op.drop_table('opcao_pergunta')
    op.drop_table('pergunta')
    op.drop_table('bloco_formulario')
    op.drop_table('auditoria')
    op.drop_table('loja')
    op.drop_table('formulario')
    op.drop_table('usuario')
    op.drop_table('grupo')
    op.drop_table('laudo_microbiologico')
    op.drop_table('cliente')
    op.drop_table('categoria_formulario')
    # ### end Alembic commands ###
