"""restore acao_corretiva_arquivo

Revision ID: 06e56346a35c
Revises: 28c7ba298586
Create Date: 2026-03-08 16:36:08.673527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e56346a35c'
down_revision = '28c7ba298586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acao_corretiva_arquivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.drop_column('acao_corretiva_arquivo')

    # ### end Alembic commands ###
