"""Add relatorio_mensal and laudo_laboratorio to AplicacaoQuestionario

Revision ID: 09fe142b1e96
Revises: 8cb077d85dc2
Create Date: 2026-03-02 11:43:34.970787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fe142b1e96'
down_revision = '8cb077d85dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relatorio_mensal_arquivo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('laudo_laboratorio_arquivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.drop_column('laudo_laboratorio_arquivo')
        batch_op.drop_column('relatorio_mensal_arquivo')

    # ### end Alembic commands ###
