"""restore fluxograma_arquivo

Revision ID: 28c7ba298586
Revises: 66ad5fd33af6
Create Date: 2026-03-08 16:18:33.397974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c7ba298586'
down_revision = '66ad5fd33af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fluxograma_arquivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.drop_column('fluxograma_arquivo')

    # ### end Alembic commands ###
