"""Adiciona hierarquia usuarios

Revision ID: 35c17abd8293
Revises: ae787048ea82
Create Date: 2026-01-18 18:09:22.375897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c17abd8293'
down_revision = 'ae787048ea82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topico', schema=None) as batch_op:
        batch_op.alter_column('ordem',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DATETIME(), nullable=True))
        batch_op.alter_column('ordem',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
