"""Adiciona hierarquia usuarios

Revision ID: 35c17abd8293
Revises: ae787048ea82
Create Date: 2026-01-18 18:09:22.375897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c17abd8293'
down_revision = 'ae787048ea82'
branch_labels = None
depends_on = None


def upgrade():
    # ### PARTE 1: TABELA USUARIO ###
    # O erro mostrou que 'cliente_id' e 'grupo_id' JÁ EXISTEM.
    # Vamos assumir que 'avaliado_id' também existe e comentar tudo para não travar.
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        # batch_op.add_column(sa.Column('grupo_id', sa.Integer(), nullable=True))
        # batch_op.add_column(sa.Column('avaliado_id', sa.Integer(), nullable=True))

        # batch_op.create_foreign_key('fk_usuario_cliente', 'cliente', ['cliente_id'], ['id'])
        # batch_op.create_foreign_key('fk_usuario_grupo', 'grupo', ['grupo_id'], ['id'])
        # batch_op.create_foreign_key('fk_usuario_avaliado', 'avaliado', ['avaliado_id'], ['id'])
        pass

    # ### PARTE 2: TABELA TOPICO ###
    with op.batch_alter_table('topico', schema=None) as batch_op:
        batch_op.alter_column('ordem',
               existing_type=sa.INTEGER(),
               nullable=True)
        # Comentado porque a coluna não existe no banco
        # batch_op.drop_column('criado_em')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Reverte as mudanças do topico
    with op.batch_alter_table('topico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DATETIME(), nullable=True))
        batch_op.alter_column('ordem',
               existing_type=sa.INTEGER(),
               nullable=False)

    # Remove as colunas de hierarquia do usuario
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usuario_avaliado', type_='foreignkey')
        batch_op.drop_constraint('fk_usuario_grupo', type_='foreignkey')
        batch_op.drop_constraint('fk_usuario_cliente', type_='foreignkey')
        batch_op.drop_column('avaliado_id')
        batch_op.drop_column('grupo_id')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
