"""Refatoracao de anexos e inclusao de DocumentoMensal

Revision ID: 66ad5fd33af6
Revises: 9659988e91a5
Create Date: 2026-03-08 14:51:17.498992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ad5fd33af6'
down_revision = '9659988e91a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_mensal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes_ano', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=255), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.drop_column('ordem_servico_2_arquivo')
        batch_op.drop_column('checklist_arquivo')
        batch_op.drop_column('relatorio_mensal_arquivo')
        batch_op.drop_column('laudo_materia_prima_arquivo')
        batch_op.drop_column('acao_corretiva_arquivo')
        batch_op.drop_column('laudo_laboratorio_arquivo')
        batch_op.drop_column('fluxograma_arquivo')
        batch_op.drop_column('manual_boas_praticas_arquivo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_boas_praticas_arquivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fluxograma_arquivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('laudo_laboratorio_arquivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('acao_corretiva_arquivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('laudo_materia_prima_arquivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('relatorio_mensal_arquivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('checklist_arquivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ordem_servico_2_arquivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.drop_table('documento_mensal')
    # ### end Alembic commands ###
