"""Adiciona visita_inicio fim e tabela acao_corretiva

Revision ID: 8cb077d85dc2
Revises: f398b593099f
Create Date: 2026-02-08 16:47:35.730351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb077d85dc2'
down_revision = 'f398b593099f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acao_corretiva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aplicacao_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('descricao_nao_conformidade', sa.Text(), nullable=False),
    sa.Column('sugestao_correcao', sa.Text(), nullable=True),
    sa.Column('acao_realizada', sa.Text(), nullable=True),
    sa.Column('foto_evidencia', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('criticidade', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aplicacao_id'], ['aplicacao_questionario.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visita_inicio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('visita_fim', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.drop_column('visita_fim')
        batch_op.drop_column('visita_inicio')

    op.drop_table('acao_corretiva')
    # ### end Alembic commands ###
