"""Add lista_presenca_arquivo to Treinamento

Revision ID: 9659988e91a5
Revises: 09fe142b1e96
Create Date: 2026-03-06 15:16:49.646173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9659988e91a5'
down_revision = '09fe142b1e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treinamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lista_presenca_arquivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treinamento', schema=None) as batch_op:
        batch_op.drop_column('lista_presenca_arquivo')

    # ### end Alembic commands ###
