"""Migração inicial com campos restringir_avaliados e reincidencia_ativa

Revision ID: 9aedbc0c18e4
Revises: 
Create Date: 2025-06-09 15:59:30.943099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aedbc0c18e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enviar_email', sa.Boolean(), nullable=True),
    sa.Column('configurar_no_final', sa.Boolean(), nullable=True),
    sa.Column('exibir_emails_anteriores', sa.Boolean(), nullable=True),
    sa.Column('idioma', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calcular_nota', sa.Boolean(), nullable=True),
    sa.Column('ocultar_nota', sa.Boolean(), nullable=True),
    sa.Column('base_calculo', sa.Integer(), nullable=True),
    sa.Column('casas_decimais', sa.Integer(), nullable=True),
    sa.Column('modo_configuracao', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exibir_nota_anterior', sa.Boolean(), nullable=True),
    sa.Column('exibir_tabela_resumo', sa.Boolean(), nullable=True),
    sa.Column('exibir_limites_aceitaveis', sa.Boolean(), nullable=True),
    sa.Column('omitir_data_hora', sa.Boolean(), nullable=True),
    sa.Column('exibir_omitidas', sa.Boolean(), nullable=True),
    sa.Column('gerar_relatorio_nc', sa.Boolean(), nullable=True),
    sa.Column('modo_exibicao_nota', sa.String(length=50), nullable=True),
    sa.Column('tipo_agrupamento', sa.String(length=50), nullable=True),
    sa.Column('cor_observacoes', sa.String(length=50), nullable=True),
    sa.Column('cor_relatorio', sa.String(length=50), nullable=True),
    sa.Column('logotipo_cabecalho', sa.String(length=255), nullable=True),
    sa.Column('logotipo_rodape', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano_saas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_plano', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_mensal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('limite_usuarios', sa.Integer(), nullable=True),
    sa.Column('limite_formularios', sa.Integer(), nullable=True),
    sa.Column('limite_auditorias', sa.Integer(), nullable=True),
    sa.Column('funcionalidades_disponiveis', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_plano')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email_contato', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_ativacao', sa.DateTime(), nullable=True),
    sa.Column('plano_saas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plano_saas_id'], ['plano_saas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('questionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('versao', sa.String(length=10), nullable=False),
    sa.Column('modo', sa.String(length=50), nullable=True),
    sa.Column('documento_referencia', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('configuracao_nota_id', sa.Integer(), nullable=True),
    sa.Column('configuracao_relatorio_id', sa.Integer(), nullable=True),
    sa.Column('configuracao_email_id', sa.Integer(), nullable=True),
    sa.Column('restringir_avaliados', sa.Boolean(), nullable=True),
    sa.Column('reincidencia_ativa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['configuracao_email_id'], ['configuracao_email.id'], ),
    sa.ForeignKeyConstraint(['configuracao_nota_id'], ['configuracao_nota.id'], ),
    sa.ForeignKeyConstraint(['configuracao_relatorio_id'], ['configuracao_relatorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campo_personalizado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('visivel', sa.Boolean(), nullable=True),
    sa.Column('pre_configurado', sa.Boolean(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_questionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_autorizado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('idioma', sa.String(length=10), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campo_personalizado_valor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campo_id', sa.Integer(), nullable=False),
    sa.Column('avaliado_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['avaliado_id'], ['avaliado.id'], ),
    sa.ForeignKeyConstraint(['campo_id'], ['campo_personalizado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('avaliado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avaliado_id'], ['avaliado.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('avaliado_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('exibir_tabela_relatorio', sa.Boolean(), nullable=True),
    sa.Column('exibir_limites_aceitaveis', sa.Boolean(), nullable=True),
    sa.Column('gerar_relatorio_nao_conformidade', sa.Boolean(), nullable=True),
    sa.Column('pontuacao_ativa', sa.Boolean(), nullable=True),
    sa.Column('criado_por_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avaliado_id'], ['avaliado.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['criado_por_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('avaliado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes_gerais', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['avaliado_id'], ['avaliado.id'], ),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bloco_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.Column('tipo_resposta', sa.Enum('SIM_NAO', 'TEXTO', 'NOTA', 'MULTIPLA_ESCOLHA', 'UNICA_ESCOLHA', 'IMAGEM', 'DATA', 'HORA', name='tiporesposta'), nullable=False),
    sa.Column('obrigatoria', sa.Boolean(), nullable=True),
    sa.Column('bloco_id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('observacao_campo', sa.Boolean(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('limite_min', sa.Float(), nullable=True),
    sa.Column('limite_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bloco_id'], ['bloco_formulario.id'], ),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcao_pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditoria_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('valor_texto', sa.Text(), nullable=True),
    sa.Column('valor_boolean', sa.Boolean(), nullable=True),
    sa.Column('valor_numero', sa.Float(), nullable=True),
    sa.Column('valor_opcoes_selecionadas', sa.Text(), nullable=True),
    sa.Column('valor_arquivo', sa.String(length=255), nullable=True),
    sa.Column('nota_obtida', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditoria.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta')
    op.drop_table('opcao_pergunta')
    op.drop_table('pergunta')
    op.drop_table('bloco_formulario')
    op.drop_table('auditoria')
    op.drop_table('formulario')
    op.drop_table('usuario')
    op.drop_table('campo_personalizado_valor')
    op.drop_table('avaliado')
    op.drop_table('usuario_autorizado')
    op.drop_table('topico')
    op.drop_table('grupo_questionario')
    op.drop_table('grupo')
    op.drop_table('campo_personalizado')
    op.drop_table('questionario')
    op.drop_table('cliente')
    op.drop_table('plano_saas')
    op.drop_table('configuracao_relatorio')
    op.drop_table('configuracao_nota')
    op.drop_table('configuracao_email')
    # ### end Alembic commands ###
