"""Sincronizacao preservando dados

Revision ID: ae787048ea82
Revises: 
Create Date: 2026-01-04 11:48:23.080061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae787048ea82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topico', schema=None) as batch_op:
        batch_op.alter_column('ordem',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DATETIME(), nullable=True))
        batch_op.alter_column('ordem',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
