"""Adiciona avaliado_id em Usuario

Revision ID: cc3cd0a152fa
Revises: cf141d41926c
Create Date: 2025-11-25 17:00:00.630280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3cd0a152fa'
down_revision = 'cf141d41926c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avaliado_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'avaliado', ['avaliado_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('avaliado_id')

    # ### end Alembic commands ###
