"""Adiciona caminho_foto a RespostaPergunta

Revision ID: cf141d41926c
Revises: f5f909665450
Create Date: 2025-10-25 11:43:15.354506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf141d41926c'
down_revision = 'f5f909665450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resposta_pergunta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caminho_foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resposta_pergunta', schema=None) as batch_op:
        batch_op.drop_column('caminho_foto')

    # ### end Alembic commands ###
