"""Reset total do banco na VPS

Revision ID: deebd4a926ff
Revises: 
Create Date: 2025-12-17 14:55:27.631602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deebd4a926ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('plano', sa.String(length=50), nullable=True),
    sa.Column('limite_usuarios', sa.Integer(), nullable=True),
    sa.Column('limite_questionarios', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('configuracao', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria_indicador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('cor_primaria', sa.String(length=7), nullable=True),
    sa.Column('cor_secundaria', sa.String(length=7), nullable=True),
    sa.Column('mostrar_notas', sa.Boolean(), nullable=True),
    sa.Column('permitir_fotos', sa.Boolean(), nullable=True),
    sa.Column('obrigar_plano_acao', sa.Boolean(), nullable=True),
    sa.Column('notificar_aplicacoes_finalizadas', sa.Boolean(), nullable=True),
    sa.Column('notificar_nao_conformidades', sa.Boolean(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('campos_personalizados', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.Enum('SUPER_ADMIN', 'ADMIN', 'GESTOR', 'AUDITOR', 'USUARIO', 'VISUALIZADOR', name='tipousuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('avaliado_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['avaliado_id'], ['avaliado.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=200), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('entidade_tipo', sa.String(length=50), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data_acao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('visualizada', sa.Boolean(), nullable=True),
    sa.Column('data_visualizacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('versao', sa.String(length=20), nullable=True),
    sa.Column('modo', sa.String(length=50), nullable=True),
    sa.Column('documento_referencia', sa.String(length=255), nullable=True),
    sa.Column('calcular_nota', sa.Boolean(), nullable=True),
    sa.Column('ocultar_nota_aplicacao', sa.Boolean(), nullable=True),
    sa.Column('base_calculo', sa.Integer(), nullable=True),
    sa.Column('casas_decimais', sa.Integer(), nullable=True),
    sa.Column('modo_configuracao', sa.String(length=20), nullable=True),
    sa.Column('modo_exibicao_nota', sa.Enum('PERCENTUAL', 'PONTOS', 'AMBOS', 'OCULTAR', name='modoexibicaonota'), nullable=True),
    sa.Column('anexar_documentos', sa.Boolean(), nullable=True),
    sa.Column('capturar_geolocalizacao', sa.Boolean(), nullable=True),
    sa.Column('restringir_avaliados', sa.Boolean(), nullable=True),
    sa.Column('habilitar_reincidencia', sa.Boolean(), nullable=True),
    sa.Column('tipo_preenchimento', sa.Enum('RAPIDO', 'DETALHADO', 'COMPLETO', name='tipopreenchimento'), nullable=True),
    sa.Column('pontuacao_ativa', sa.Boolean(), nullable=True),
    sa.Column('exibir_nota_anterior', sa.Boolean(), nullable=True),
    sa.Column('exibir_tabela_resumo', sa.Boolean(), nullable=True),
    sa.Column('exibir_limites_aceitaveis', sa.Boolean(), nullable=True),
    sa.Column('exibir_data_hora', sa.Boolean(), nullable=True),
    sa.Column('exibir_questoes_omitidas', sa.Boolean(), nullable=True),
    sa.Column('exibir_nao_conformidade', sa.Boolean(), nullable=True),
    sa.Column('cor_relatorio', sa.Enum('AZUL', 'VERDE', 'VERMELHO', 'LARANJA', 'ROXO', 'CINZA', name='correlatorio'), nullable=True),
    sa.Column('incluir_assinatura', sa.Boolean(), nullable=True),
    sa.Column('incluir_foto_capa', sa.Boolean(), nullable=True),
    sa.Column('agrupamento_fotos', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'PUBLICADO', 'ARQUIVADO', 'INATIVO', name='statusquestionario'), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aplicacao_questionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('EM_ANDAMENTO', 'FINALIZADA', 'CANCELADA', 'PAUSADA', name='statusaplicacao'), nullable=True),
    sa.Column('nota_final', sa.Float(), nullable=True),
    sa.Column('pontos_obtidos', sa.Float(), nullable=True),
    sa.Column('pontos_totais', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('observacoes_finais', sa.Text(), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('endereco_capturado', sa.String(length=255), nullable=True),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.Column('avaliado_id', sa.Integer(), nullable=False),
    sa.Column('aplicador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aplicador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['avaliado_id'], ['avaliado.id'], ),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_indicador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_indicador_id'], ['categoria_indicador.id'], ),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_autorizado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('SIM_NAO_NA', 'MULTIPLA_ESCOLHA', 'ESCALA_NUMERICA', 'NOTA', 'TEXTO_CURTO', 'TEXTO_LONGO', 'FOTO', 'DATA', 'HORA', 'NUMERO', 'PORCENTAGEM', 'MOEDA', 'ASSINATURA', name='tiporesposta'), nullable=False),
    sa.Column('obrigatoria', sa.Boolean(), nullable=True),
    sa.Column('permite_observacao', sa.Boolean(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('exige_foto_se_nao_conforme', sa.Boolean(), nullable=False),
    sa.Column('configuracoes', sa.Text(), nullable=True),
    sa.Column('topico_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topico_id'], ['topico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcao_pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta_pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('pontos', sa.Float(), nullable=True),
    sa.Column('caminho_foto', sa.String(length=255), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('tempo_resposta', sa.Integer(), nullable=True),
    sa.Column('nao_conforme', sa.Boolean(), nullable=True),
    sa.Column('plano_acao', sa.Text(), nullable=True),
    sa.Column('prazo_plano_acao', sa.Date(), nullable=True),
    sa.Column('responsavel_plano_acao', sa.String(length=100), nullable=True),
    sa.Column('aplicacao_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aplicacao_id'], ['aplicacao_questionario.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta_pergunta')
    op.drop_table('opcao_pergunta')
    op.drop_table('pergunta')
    op.drop_table('usuario_autorizado')
    op.drop_table('topico')
    op.drop_table('aplicacao_questionario')
    op.drop_table('questionario')
    op.drop_table('notificacao')
    op.drop_table('log_auditoria')
    op.drop_table('usuario')
    op.drop_table('avaliado')
    op.drop_table('grupo')
    op.drop_table('configuracao_cliente')
    op.drop_table('categoria_indicador')
    op.drop_table('integracao')
    op.drop_table('cliente')
    # ### end Alembic commands ###
