"""Adiciona campos de assinatura

Revision ID: f398b593099f
Revises: 35c17abd8293
Create Date: 2026-01-23 13:46:10.291748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f398b593099f'
down_revision = '35c17abd8293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_imagem', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('assinatura_responsavel', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cargo_responsavel', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplicacao_questionario', schema=None) as batch_op:
        batch_op.drop_column('cargo_responsavel')
        batch_op.drop_column('assinatura_responsavel')
        batch_op.drop_column('assinatura_imagem')

    # ### end Alembic commands ###
