"""Adiciona campo exige_foto_se_nao_conforme a Pergunta

Revision ID: f5f909665450
Revises: 
Create Date: 2025-10-25 11:20:47.097386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f909665450'
down_revision = None # Se esta for sua PRIMEIRA migração, down_revision = None está correto.
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite NOT NULL ###
    with op.batch_alter_table('pergunta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exige_foto_se_nao_conforme', sa.Boolean(), 
                                       nullable=False, 
                                       server_default=sa.false())) # <-- CORREÇÃO APLICADA AQUI

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pergunta', schema=None) as batch_op:
        batch_op.drop_column('exige_foto_se_nao_conforme')

    # ### end Alembic commands ###